name: DAG size updater

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.DAG_TOKEN }}
      - name: Install node
        uses: actions/setup-node@v3.5.1
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Run update script
        run: |
            npm install node-fetch --no-save
            node internal/alfurDagUpdater
      - name: Push
        run: |
            git config user.name UhhhAaron
            git config user.email 28939026+UhhhAaron@users.noreply.github.com
            git add .
            git commit -m "Maintenance: Update DAG sizes"
            git push
